name: warqna_mobile
publish_to: none
description: Warqna premium social card games app for Android, iOS and Web.
version: 1.55.0+155

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  image_picker: ^1.2.3
  google_mobile_ads: 7.0.0
  flutter_webrtc: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/design-reference.png
    - assets/images/pasha.png
