@extends('layouts.app')
@section('content')
@php $online=$club->members->filter(fn($m)=>$m->user?->last_seen_at && $m->user->last_seen_at->gt(now()->subMinutes(5))); @endphp
<div class="club-page-shell">
 <section class="club-profile-hero pro-card">
  <div class="club-emblem big">👥</div>
  <div><h1>{{$club->name}}</h1><p>المالك: <b>{{$club->owner?->username}}</b> • تاريخ الإنشاء: {{$club->created_at?->format('Y-m-d')}}</p><div class="club-meta-row"><span class="club-league-badge">{{$clubLeagues[min(6,max(1,$club->level))] ?? 'برونزي'}}</span><span class="pill">Level {{$club->level}}</span><span class="pill">{{$club->members->count()}}/{{$clubCaps[min(6,max(1,$club->level))] ?? 50}}</span><span class="pill online-pill">🟢 {{$online->count()}} Online</span><span class="pill">🪙 {{number_format($club->treasury)}}</span></div></div>
  @if($club->owner_id===auth()->id() || auth()->user()->is_admin)
  <form method="post" action="{{route('clubs.delete',$club)}}" data-confirm="هل تريد حذف المجموعة نهائيًا؟ سيتم حذف الأعضاء والطلبات الخاصة به.">@csrf<button class="danger">حذف المجموعة نهائيًا</button></form>
  @endif
 </section>
 <section class="pro-card v105-club-economy"><h2>📊 نظام المجموعة</h2><div class="system-grid"><span>الدوري الحالي: {{$clubLeagues[min(6,max(1,$club->level))] ?? 'برونزي'}}</span><span>السعة: {{$clubCaps[min(6,max(1,$club->level))] ?? 20}}</span><span>نقاط أسبوعية: {{$club->weekly_points}}</span><span>الخزنة: 🪙 {{number_format($club->treasury)}}</span><span>اللعب الجماعي يعطي Bonus x2</span><span>المالك/المشرف يوزع الخزنة حسب الصلاحيات</span></div></section>
 <section class="pro-card"><h2>اللاعبون الموجودون الآن</h2><div class="club-online-list">@forelse($online as $m)<button type="button" onclick="openProfile({{$m->user_id}})"><img src="{{$m->user?->profile?->avatar ?: '/assets/avatars/default.svg'}}">{{$m->user?->username}}</button>@empty<p class="muted">لا يوجد أعضاء Online حاليًا.</p>@endforelse</div></section>
 <section class="pro-card"><h2>أعضاء المجموعة</h2><div class="club-member-table">@foreach($club->members as $m)<div class="club-member-row"><button type="button" class="user-chip" onclick="openProfile({{$m->user_id}})"><img class="avatar-xs" src="{{$m->user?->profile?->avatar ?: '/assets/avatars/default.svg'}}">{{$m->user?->username}}</button><span class="pill">{{$m->role}}</span><span>نقاط: {{$m->weekly_points}}</span><small>{{($m->user?->last_seen_at && $m->user->last_seen_at->gt(now()->subMinutes(5)))?'Online':'Offline'}}</small>@if(($club->owner_id===auth()->id() || auth()->user()->is_admin) && $m->role!=='owner')<form class="club-permission-form" method="post" action="{{route('clubs.memberAction',[$club,$m])}}">@csrf<input type="hidden" name="action" value="moderator"><label><input type="checkbox" name="accept_members" {{$m->permissions['accept_members']??false?'checked':''}}> قبول</label><label><input type="checkbox" name="kick_members" {{$m->permissions['kick_members']??false?'checked':''}}> طرد</label><label><input type="checkbox" name="create_tournaments" {{$m->permissions['create_tournaments']??false?'checked':''}}> مسابقات</label><label><input type="checkbox" name="manage_chat" {{$m->permissions['manage_chat']??false?'checked':''}}> دردشة</label><button>جعله مشرف</button></form><form method="post" action="{{route('clubs.memberAction',[$club,$m])}}" data-confirm="هل تريد طرد هذا اللاعب؟">@csrf<input type="hidden" name="action" value="kick"><button class="danger">طرد</button></form>@endif</div>@endforeach</div></section>
 @if($canAccept)
 <section class="pro-card"><h2>طلبات الانضمام</h2>@forelse($club->joinRequests->where('status','pending') as $req)<form class="inline-card" method="post" action="{{route('clubs.respond',$req)}}">@csrf<b>{{$req->user->username}}</b><button class="success" name="status" value="accepted">قبول</button><button class="danger" name="status" value="rejected">رفض</button></form>@empty<p class="muted">لا توجد طلبات معلقة.</p>@endforelse</section>
 @endif
 <div class="club-actions-row"><a class="btn" href="{{route('clubs')}}">العودة للمجموعات</a>@if($club->members->where('user_id',auth()->id())->count())<form method="post" action="{{route('clubs.leave',$club)}}" data-confirm="هل تريد مغادرة المجموعة؟">@csrf<button class="danger">مغادرة المجموعة</button></form>@else<form method="post" action="{{route('clubs.join',$club)}}">@csrf<button>طلب انضمام</button></form>@endif</div>
</div>
@endsection
